# Generated by Django 6.1 on 2026-08-28 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drugs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterfeitFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("scan_count_at_flag", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "raised_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if raised automatically by the system",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="drugs.verificationcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_entered", models.CharField(max_length=20)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("authentic", "Authentic"),
                            ("invalid_code", "Invalid Code"),
                            ("expired", "Expired Drug"),
                            ("recalled", "Recalled/Deactivated"),
                            ("suspicious", "Suspicious (Excessive Scans)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("location_hint", models.CharField(blank=True, max_length=255)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_logs",
                        to="drugs.verificationcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
                "indexes": [
                    models.Index(
                        fields=["code_entered"], name="verificatio_code_en_7170b3_idx"
                    ),
                    models.Index(
                        fields=["result"], name="verificatio_result_d2814d_idx"
                    ),
                ],
            },
        ),
    ]
