# Generated by Django 6.1 on 2026-08-28 20:14

import django.db.models.deletion
import drugs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manufacturers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("generic_name", models.CharField(blank=True, max_length=255)),
                ("nafdac_reg_number", models.CharField(max_length=100, unique=True)),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup"),
                            ("injection", "Injection"),
                            ("cream", "Cream/Ointment"),
                            ("other", "Other"),
                        ],
                        default="tablet",
                        max_length=20,
                    ),
                ),
                ("strength", models.CharField(help_text="e.g. 500mg", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("active_ingredients", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drugs",
                        to="manufacturers.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DrugBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("quantity_produced", models.PositiveIntegerField()),
                ("manufacture_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="drugs.drug",
                    ),
                ),
            ],
            options={
                "ordering": ["-manufacture_date"],
                "unique_together": {("drug", "batch_number")},
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=drugs.models.generate_verification_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="drugs.drugbatch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="drugs_verif_code_67e105_idx")
                ],
            },
        ),
    ]
